window.fichaNames = {
  "DG-PSEA-01": "Protocolo general de participacion EA",
  "DG-PSEA-02": "Aplicativo `calaire-app`",
  "DG-PSEA-03": "Aplicativo `pt_app`",
  "F-PSEA-01": "Calendario global de ronda",
  "F-PSEA-02": "Cronograma detallado de ronda",
  "F-PSEA-03": "Registro de participacion",
  "F-PSEA-04": "Anexo tecnico de equipos e instrumentos del participante",
  "F-PSEA-05": "Plan de ronda EA",
  "F-PSEA-05A": "Hoja de registro del participante",
  "F-PSEA-06": "Ficha digital de ronda EA",
  "F-PSEA-07": "Preparacion y control del item",
  "F-PSEA-08": "Datos reportados por participante",
  "F-PSEA-09": "Datos de participantes exportados para analisis PT",
  "F-PSEA-10": "Registro de preprocesamiento de datos",
  "F-PSEA-11": "Homogeneidad y estabilidad del item",
  "F-PSEA-11A": "Datos preprocesados de homogeneidad",
  "F-PSEA-11B": "Datos preprocesados de estabilidad",
  "F-PSEA-11C": "Resultados de homogeneidad",
  "F-PSEA-11D": "Resultados de estabilidad",
  "F-PSEA-12": "Datos oficiales consolidados para evaluacion de aptitud",
  "F-PSEA-13": "Informe final de resultados",
  "F-PSEA-14": "Registro/caso de queja o NC segun aplique",
  "F-PSEA-15": "Registro de apelaciones",
  "F-PSEA-16": "Matriz de competencia/autorizacion",
  "F-PSEA-17": "Evaluacion de proveedores criticos",
  "F-PSEA-18": "Comunicacion participantes",
  "I-PSEA-02": "Instructivo de uso de `calaire-app` por participante",
  "I-PSEA-03": "Instructivo de administracion de rondas en `calaire-app`",
  "I-PSEA-04": "Instructivo de uso del preprocesador de datos de `pt_app`",
  "I-PSEA-05": "Instructivo de uso del modulo de analisis PT de `pt_app`",
  "P-PSEA-01": "Protocolo general EA",
  "P-PSEA-02": "Matriz documental basica del PEA",
  "P-PSEA-03": "Control de registros y evidencias del PEA",
  "P-PSEA-04": "Planificacion de ronda EA",
  "P-PSEA-05": "Comunicaciones del PEA",
  "P-PSEA-06": "Preparacion y control del item de ensayo gaseoso",
  "P-PSEA-07": "Diseno estadistico",
  "P-PSEA-08": "Flujo tecnico de datos digitales del PEA",
  "P-PSEA-09": "Generacion/emision del informe de resultados",
  "P-PSEA-10": "Procedimiento tecnico NO/NO2",
  "P-PSEA-11": "Procedimiento tecnico CO",
  "P-PSEA-12": "Procedimiento tecnico O3",
  "P-PSEA-13": "Procedimiento tecnico SO2",
  "P-PSEA-14": "Colusion y falsificacion",
  "P-PSEA-15": "Trabajo no conforme, no conformidades y acciones correctivas",
  "P-PSEA-16": "Divulgacion y control de valores sensibles",
  "P-PSEA-17": "Quejas del PEA",
  "P-PSEA-18": "Apelaciones del PEA",
  "P-PSEA-19": "Confidencialidad operativa interna del PEA",
  "P-PSEA-20": "Competencia y autorizacion operativa del PEA",
  "P-PSEA-21": "Proveedores criticos del PEA",
  "P-PSEA-22": "Riesgos generales del PEA",
  "P-PSEA-23": "Mejora continua del PEA"
};
